name: Keep Supabase Awake

on:
  schedule:
    - cron: "0 0 */3 * *"   # runs every 3 days
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Supabase
        run: |
          curl -X GET "https://njrxegrvkjnzylvxbkjj.supabase.co/rest/v1/"